config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents, only: %i[new create index destroy]
  root to: 'documents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[destroy]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      flash[:success] = 'File saved'
      redirect_to documents_path
    else
      render 'new'
    end
  end

  def destroy
    @document.destroy
    if @document.destroyed?
      flash[:success] = 'File deleted'
    else
      flash[:error] = 'Unable to delete file, please contact the administrator'
    end
    redirect_to documents_path
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<h3>List of files</h3>

<%= link_to 'Add your file', new_document_path, class: 'btn btn-lg btn-primary' %>

<ul class="row" id="files-list">
  <% @documents.each do |document| %>
    <li class="col-xs-3">
      <%= link_to document.file.filename, url_for(document.file), target: '_blank' %>
    </li>
    <li>
      <%= link_to 'download', rails_blob_url(document.file, disposition: "attachment") %>
      <%= link_to 'delete', document, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/documents/new.html.erb
<h3>New file</h3>

<%= form_with(model: @document, local: true) do |form| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :file %>
    <%= form.file_field :file, required: true, direct_upload: true %>
  </div>

  <%= form.submit 'Submit', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dropbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Dropbox.ng</h1>
    <%= yield %>
  </body>
</html>